# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
defaults:
  run:
    - name: gitflow-action
  uses: Logerfo/gitflow-action@0.0.4
  with:
    # The `GITHUB_TOKEN` secret.
    github-token: 
    # The `release` branch.
    release: # optional, default is release
    # The `dev` branch.
    dev: # optional, default is dev
    # The `master` branch.
    master: # optional, default is master
    # The pull request label.
    label: # optional, default is gitflow
    # If `true`, will try to automatically merge pull requests. Can also be set to `pull_request_review`, `check_run`, `push`, or a comma-separated combination of these values to only merge when handling the named events.
    auto-merge: # optional, default is true
    # If an attempted merge fails, the action is considered to have failed.
    require-merge: # optional
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
